#cloud-config
#doctl compute droplet create dydobuild.do.alteiria.fr --enable-ipv6 --image 50944795 --region ams3 --ssh-keys 25332773 --volumes "caa37ab3-6c49-11ea-98bc-0a58ac1480a1" --user-data-file=/home/emilien/Documents/dynamicDigitalocean/vm/cloudinit.yaml --size s-2vcpu-4gb --wait
#doctl compute droplet delete dydobuild.do.alteiria.fr -f
#doctl compute volume create --size 5GiB --fs-type ext4 --region ams3 dydobuild

timezone: Europe/Paris

mounts:
    - [ sda, /srv, auto, "defaults" ]

runcmd:
  - [ufw, disable]
  - [
      wget,
      "https://github.com/Alteiria/dynamicDigitalocean/raw/master/vm/init.sh",
      "-O",
      "/var/tmp/init.sh",
    ]
  - ["bash", "/var/tmp/init.sh"]

write_files:
  - content: ewogImRhdGEtcm9vdCI6ICIvc3J2L2RvY2tlciIsCiAibG9nLWRyaXZlciI6ICJqc29uLWZpbGUiLAogImxvZy1vcHRzIjogeyJtYXgtc2l6ZSI6ICIxMG0iLCAibWF4LWZpbGUiOiAiMyJ9Cn0=
    encoding: b64
    owner: "root:root"
    path: /etc/docker/daemon.json
    permissions: "0644"

swap:
  filename: /swap.img
  size: "auto"
  maxsize: 5368709120