version: "3"
services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        environment:
            - URL=${HOSTNAME}
            - VALIDATION=http
        volumes:
            - "/srv/letsencrypt:/config"
        restart: always
        ports:
            - 80:80
    
    checker:
        depends_on:
            - daemon
        image: alteiria/dynamicdigitalocean
        restart: always
        networks:
            - default
        volumes:
            - /srv/daemon/config:/config
            - /etc/hostname
        environment:
            - DO_API_TOKEN=${DO_API_TOKEN}
            - HOSTNAME=${HOSTNAME}
            - SLEEP_MIN=${SLEEP_MIN:-30}

    daemon:
        depends_on:
            - letsencrypt
        image: ccarney16/pterodactyl-daemon:latest
        ports:
            - 8080:8080
            - 2022:2022
        privileged: true
        restart: always
        networks:
            - default
        volumes:
            - /srv/daemon/config:/srv/daemon/config
            - /srv/daemon/packs:/srv/daemon/packs
            - /srv/daemon-data:/srv/daemon-data
            - /srv/letsencrypt/etc/letsencrypt:/etc/letsencrypt
            - /tmp/pterodactyl:/tmp/pterodactyl
            - /etc/localtime:/etc/localtime
            - /srv/docker:/srv/docker
            - /var/run/docker.sock:/var/run/docker.sock
    watchtower:
        image: containrrr/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 --cleanup

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"