version: "3"
services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        environment:
            - URL=${HOSTNAME}
            - VALIDATION=http
        volumes:
            - "/srv/letsencrypt:/config"
        restart: always
        ports:
            - 80:80

    daemon:
        depends_on:
            - letsencrypt
        image: ccarney16/pterodactyl-daemon:latest
        ports:
            - 443:443
            - 2022:2022
        privileged: true
        restart: always
        networks:
            - default
        volumes:
            - /srv/daemon/config:/srv/daemon/config
            - /srv/daemon/packs:/srv/daemon/packs
            - /srv/daemon-data:/srv/daemon-data
            - /srv/letsencrypt/etc/letsencrypt:/etc/letsencrypt
            - /tmp/pterodactyl:/tmp/pterodactyl
            - /etc/localtime:/etc/localtime
            - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
            - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"